#FROM leiserfg/zola:latest
#WORKDIR /workdir
#COPY . /workdir
##RUN /usr/bin/zola build
##ENTRYPOINT ["/usr/bin/zola", "build"]
#CMD ["/usr/bin/zola", "serve", "-i", "0.0.0.0"]
#
#FROM nginx:mainline-alpine
#RUN rm /etc/nginx/conf.d/*
#ADD hello.conf /etc/nginx/conf.d/
#RUN cp /workdir/public/* /usr/share/nginx/html/ 

#FROM jakeswenson/zola
#COPY . /workdir
#RUN /usr/bin/zola build

FROM nginx:stable

ENV ZOLA_VERSION=v0.8.0

RUN curl -L https://github.com/getzola/zola/releases/download/$ZOLA_VERSION/zola-$ZOLA_VERSION-x86_64-unknown-linux-gnu.tar.gz > zola.tar.gz \
  && tar xvf zola.tar.gz \
  && mv zola /usr/bin/ \
  && rm -rf zola.tar.gz

WORKDIR /zola
COPY . /zola
RUN zola build
RUN mkdir /usr/share/nginx/html/alonsomoya.com && cp -r /zola/public/* /usr/share/nginx/html/alonsomoya.com
